version: '3'

services:
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./redis:/data/redis"

    postgresql:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - "./postgres/init:/data/postgresql"
        environment:
            POSTGRES_USER: shumiya
            POSTGRES_PASSWORD: shumiya
            POSTGRES_DB: ahp
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

